#!/bin/bash
# CronWrapper - sources ~/bin/SetUp
#               runs command, writes log files (stdout and stderr) to ~/log directory
#               cron errors can be found in the account's mailbox
#
# Usage:  (in cron table)
#         (1)  /home/oss/bin/CronWrapper command arg1 arg2 arg3 etc ...
#              runs "command" with the specified arguments
#              stdout from "command" goes to file logs/CronWrapper.command.<timestamp>.PID.stdout
#              stderr from "command" goes to file logs/CronWrapper.command.<timestamp>.PID.stderr
#              Any error messages from cron (eg if the command doesn't exist) go to the account's mailbox.
#         (2)  /home/oss/bin/CronWrapper
#              When run with no parameters, CronWrapper performs housekeeping on the logs directory
#              Empty stderr files older than 1 week are removed.
#              All log files older than one month are removed.

. ~/bin/SetUp

DATE=$(date +%Y%m%d.%H%M)
CRONNAME=${1##*/}       # remove directory name
LOGFILE=~/log/CronWrapper.$CRONNAME.$DATE.$$.log

if (( $# > 0));then
    exec "$@" > $LOGFILE 2> ${LOGFILE}.stderr
else
    # remove empty stderr files (older than 1 day)
    find ~/log/. -name 'CronWrapper.*.stderr' -size 0 -mtime +0 -exec rm {} \;

    # remove files (older than 1 month)
    find ~/log/. -name 'CronWrapper.*' -mtime +31 -exec rm {} \;
fi
